cv/urls.py
from django.urls import re_path,path 
from .views import *

app_name = 'cv'

urlpatterns = [
	path('list/',resume_list,name='list'),
	path('create/',create_resume,name='create'),
    re_path(r'^print/(?P<pk>\d+)/$',preview_resume,name='print'),
    re_path(r'^edit/(?P<pk>\d+)/$',preview_resume,name='edit'),
    re_path(r'^preview/(?P<pk>\d+)/$',preview_resume,name='preview'),
    re_path(r'^delete/(?P<pk>\d+)/$',delete_resume,name='delete'),

]

resume/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('',include('cv.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cv/models.py
from django.db import models
from django.conf import settings
# Create your models here.

User = settings.AUTH_USER_MODEL

class Resume(models.Model):
    name = models.CharField('姓名', max_length=50)
    position = models.CharField('职位', max_length=50)
    profile = models.TextField('基本信息',default="")
    contact = models.TextField('联系方式',default="")
    # skill = models.TextField('技能')
    stack = models.TextField('技术栈',default="")
    education = models.TextField('教育信息',default="")
    work = models.TextField('工作经历',default="")
    project = models.TextField('个人项目',default="")
    trophy = models.TextField('奖项与证书',default="")
    aboutme = models.TextField('自我评价',default="")
    created = models.DateTimeField('创建时间', auto_now_add=True)
    user = models.ForeignKey(User, related_name='user',on_delete=models.CASCADE)


    def __str__(self):
        return '{}-{}'.format(self.name,self.position)

    class Meta:
        verbose_name='简历信息'
        verbose_name_plural = verbose_name

cv/views.py
from django.shortcuts import render,get_object_or_404,redirect
from accounts.models import User
from .models import Resume
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.core.paginator import Paginator
import json

from io import BytesIO
from django.template.loader import get_template
# from xhtml2pdf import pisa

@login_required
def resume_list(request):
    user = get_object_or_404(User,id=request.user.id)
    resume_list = Resume.objects.filter(user=user).order_by('-created')
    if resume_list:
        paginator = Paginator(resume_list,5)
        page = request.GET.get('page')
        page_obj = paginator.get_page(page)
        return render(request,'cv/resume_list.html',{'page_obj':page_obj,'paginator':paginator,'is_paginated':True,})
    else:
        return render(request,'cv/resume_list.html')

def handle(a,b):
    return json.dumps(list(zip(a,b)))

@login_required
@csrf_exempt
def create_resume(request):
    user = User.objects.get(id=request.user.id)
    if request.method == "POST":
        post_data = request.POST.dict()
        post_data_key = list(post_data.keys())[0]
        data = json.loads(post_data_key)[0]
        judge = False
        if 'number' in data.keys():
            judge = Resume.objects.filter(pk=int(data['number']))
        if judge:
            resume = Resume.objects.get(pk=int(data['number']))
            resume.name=data['name']
            resume.position=data['position']
            resume.profile=handle(data['profile'][0],data['profile'][1])
            resume.contact=handle(data['contact'][0],data['contact'][1])
            resume.stack=handle(data['stack'][0],data['stack'][1])
            resume.education=handle(data['education'][0],data['education'][1])
            resume.work=handle(data['work'][0],data['work'][1])
            resume.project=handle(data['project'][0],data['project'][1])
            resume.trophy=handle(data['trophy'][0],data['trophy'][1])
            resume.aboutme=data['aboutme']
            resume.save()
            return JsonResponse({'msg': 'success'})
        else:
            resume = Resume(name=data['name'],
                            position=data['position'],
                            profile=handle(data['profile'][0],data['profile'][1]),
                            contact=handle(data['contact'][0],data['contact'][1]),
                            stack=handle(data['stack'][0],data['stack'][1]),
                            education=handle(data['education'][0],data['education'][1]),
                            work=handle(data['work'][0],data['work'][1]),
                            project=handle(data['project'][0],data['project'][1]),
                            trophy=handle(data['trophy'][0],data['trophy'][1]),
                            aboutme=data['aboutme'],
                            user=user)
            resume.save()
            return JsonResponse({'msg': 'success'})
    else:
        return render(request,'accounts/resume.html')

@login_required
def edit_resume(request,pk):
    pass

'''
    预览并打印PDF，依赖于 xhtml2pdf 包，但是不支持中文打印以及一些 css 样式
    可以在模板中 style 中添加
    @font-face {
    font-family: simsun;    
    src: url(C:/Windows/Fonts/simsun.ttc);
    }

'''
# def render_to_pdf(template_src, context={}):
#     template = get_template(template_src)
#     html  = template.render(context)
#     result = BytesIO()
#     pdf = pisa.pisaDocument(BytesIO(html.encode("utf-8")), result)
#     if not pdf.err:
#         return HttpResponse(result.getvalue(), content_type='application/pdf')
#     return None 

@login_required
def preview_resume(request,pk):
    # pdf = render_to_pdf('cv/pdf.html', {})
    # return HttpResponse(pdf, content_type='application/pdf')
    resume = get_object_or_404(Resume,pk=pk)
    context = {
        "number":resume.id,
    	"name":resume.name,
    	"position":resume.position,
    	"profile":json.loads(resume.profile),
    	"contact":json.loads(resume.contact),
    	"stack":json.loads(resume.stack),
    	"education":json.loads(resume.education),
    	"work":json.loads(resume.work),
    	"project":json.loads(resume.project),
    	"trophy":json.loads(resume.trophy),
    	"aboutme":resume.aboutme,
        "print":True if request.path == '/print/{}/'.format(resume.id) else False,
        "edit":True if request.path == '/edit/{}/'.format(resume.id) else False,
        "preview":True if request.path == '/preview/{}/'.format(resume.id) else False,
    }
    return render(request,'cv/preview_resume.html',context=context)

@login_required
def delete_resume(request,pk):
    resume = Resume.objects.get(pk=pk)
    resume.delete()
    return HttpResponseRedirect(reverse('cv:list'))

cv/templates/cv/preview_resume.html
{% load staticfiles %}
{% load static %}


<link rel="stylesheet" href="{% static '/resume/css/style.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/remodal/1.1.0/remodal.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/remodal/1.1.0/remodal-default-theme.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/remodal/1.1.0/remodal.min.js"></script>
{% if edit %}
<link rel="stylesheet" href='{% static "/webpage/css/bootstrap.min.css" %}'>  
<script src="{% static '/resume/js/script.js' %}"></script>
{% include 'accounts/navbar.html' %}
{% endif %}
<div class="container" id="cv">
    <input type="hidden" value="{{ number }}">
    <div class="side">
        <div class="me">
            <div class="portrait"></div>
            <h1 id="username" >{{ name }}</h1>
            <h4 id="persona-tag" >{{ position }}</h4>
        </div>
        {% if profile %}
        <div class="profile info-unit">
            <h2 class="info-header"><i class="iconfont icon-person"></i> <span class="info-title">基本信息</span></h2>
            <hr>
            <ul class="info-list">
                {% for profile_info in profile %}
                    <li><label class="left-label">{{ profile_info.0 }}</label><span class="label-value">{{ profile_info.1 }}</span></li>
                {% endfor %}
            </ul>
        </div>    
        {% endif %}
        {% if contact %}
        <div class="contact info-unit">
            <h2 class="info-header"><i class="iconfont icon-call"></i> <span class="info-title">联系方式</span></h2>
            <hr>
            <ul class="info-list">
                {% for info in contact %}
                    <li><label class="left-label">{{ info.0 }}</label><span class="label-value">{{ info.1 }}</span></li>
                {% endfor %}
            </ul>
        </div>    
        {% endif %}
        {% if stack %}
        <div class="stack info-unit">
            <h2 class="info-header"><i class="iconfont icon-build"></i> <span class="info-title">技术栈</span></h2>
            <hr>
            <ul class="stack-list">
                {% for info in stack %}
                    <li><label class="left-label">{{ info.0 }}</label><span class="label-value">{{ info.1 }}</span></li>
                {% endfor %}
            </ul>
        </div>    
        {% endif %}
    </div>
    <div class="main">
        {% if education %}
        <div class="education info-unit right-list">
            <h2 class="info-header"><i class="iconfont icon-education"></i> <span class="info-title">教育经历</span></h2>
            <hr>
            <ul class="experience-list">
                {% for info in education %}
                <li>
                    <h3>{{ info.0 }}</h3>
                    <p>{{ info.1 }} </p>
                </li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        {% if work %}
        <div class="work info-unit right-list">
            <h2 class="info-header"><i class="iconfont icon-work"></i> <span class="info-title">工作经历</span></h2>
            <hr>
            <ul class="experience-list">
                {% for info in work %}
                <li>
                    <h3>{{ info.0 }}</h3>
                    <p>{{ info.1 }} </p>
                </li>
                {% endfor %}
            </ul class="experience-list">
        </div>            
        {% endif %}
        {% if project %}
        <div class="project info-unit right-list">
            <h2 class="info-header"><i class="iconfont icon-project"></i> <span class="info-title">个人项目</span></h2>
            <hr>
            <ul class="experience-list">
                {% for info in project %}
                <li>
                    <h3>{{ info.0 }}</h3>
                    <p>{{ info.1 }} </p>
                </li>
                {% endfor %}
            </ul>
        </div>   
        {% endif %}
        {% if trophy %}
        <div class="trophy info-unit">
            <h2 class="info-header"><i class="iconfont icon-trophy"></i> <span class="info-title">奖项与证书</span></h2>
            <hr>
            <ul class="experience-list">
                {% for info in trophy %}
                <li>
                    <h3>{{ info.0 }}</h3>
                    <p>{{ info.1 }} </p>
                </li>
                {% endfor %}
            </ul>                    
        </div>  
        {% endif %}

        {% if aboutme %}
        <div class="aboutme info-unit right-paragraph">
            <h2 class="info-header"><i class="iconfont icon-flower"></i> <span class="info-title">自我评价</span></h2>
            <hr>
            <p>
                {{ aboutme }}
            </p>
        </div>
        {% endif %}
        
    </div>
</div>

{% if print %}
<script>
$(document).ready(function() {
    window.print();
});
</script>
{% endif %}
{% if edit %}
<script type="text/javascript">


function JsonData()
{
window.JSONARR = [];
getValue();

function getValue() {

    var side = document.getElementsByClassName("side")[0];

    var me = side.getElementsByClassName("me")[0];
    var name = me.getElementsByTagName("h1")[0].innerText;
    var position = me.getElementsByTagName("h4")[0].innerText;
    
    if(document.getElementsByClassName("profile").length){
        var profile_list = [];
        var profile_info = side.getElementsByClassName("profile")[0];
        var profile = profile_info.getElementsByTagName("li");
        if(profile_info){
            var left_label = [];label_value = [];
            for(var i=0;i<profile.length;i++){
                left_label.push(profile[i].getElementsByClassName("left-label")[0].innerText);
                label_value.push(profile[i].getElementsByClassName("label-value")[0].innerText);
            }
            profile_list.push(left_label,label_value);
        }
    }else{
        var profile_list = [[],[]];
    }
    
    if(document.getElementsByClassName("contact").length){
        var contact_list = [];
        var contact_info = side.getElementsByClassName("contact")[0];
        var contact = contact_info.getElementsByTagName("li");
        if(contact_info){
            var left_label = [];label_value = [];
            for(var i=0;i<contact.length;i++){
                left_label.push(contact[i].getElementsByClassName("left-label")[0].innerText);
                label_value.push(contact[i].getElementsByClassName("label-value")[0].innerText);
            }
            contact_list.push(left_label,label_value);
        }
    }else{
        var contact_list = [[],[]];
    }
    
    if(document.getElementsByClassName("stack").length){
        var stack_list = [];
        var stack_info = side.getElementsByClassName("stack")[0];
        var stack = stack_info.getElementsByTagName("li");
        if(stack_info){
            var left_label = [];label_value = [];
            for(var i=0;i<stack.length;i++){
                left_label.push(stack[i].getElementsByClassName("left-label")[0].innerText);
                label_value.push(stack[i].getElementsByClassName("label-value")[0].innerText);
            }
            stack_list.push(left_label,label_value)
        }
    }else{
        var stack_list = [[],[]];
    }
    var main = document.getElementsByClassName("main")[0];
    
    if(document.getElementsByClassName("education").length){
        var education_list = [];
        var education_info = main.getElementsByClassName("education")[0];
        var education = education_info.getElementsByTagName("li");
        if(education_info){
            var h = [];p = [];
            for(var i=0;i<education.length;i++){
                h.push(education[i].getElementsByTagName("h3")[0].innerText);
                p.push(education[i].getElementsByTagName("p")[0].innerText);
            }
            education_list.push(h,p);
        }
    }else{
        var education_list = [[],[]];
    }
    
    if(document.getElementsByClassName("education").length){
        var work_list = [];
        var work_info = main.getElementsByClassName("work")[0];
        var work = work_info.getElementsByTagName("li");
        if(work_info){
            var h = [];p = [];
            for(var i=0;i<work.length;i++){
                h.push(work[i].getElementsByTagName("h3")[0].innerText);
                p.push(work[i].getElementsByTagName("p")[0].innerText);
            }
            work_list.push(h,p);
        }
    }else{
        var work_list = [[],[]];
    }
    
    if(document.getElementsByClassName("education").length){
        var project_list =[];
        var project_info = main.getElementsByClassName("project")[0];
        var project = project_info.getElementsByTagName("li");
        if(project_info){
            var h = [];p = [];
            for(var i=0;i<project.length;i++){
                h.push(project[i].getElementsByTagName("h3")[0].innerText);
                p.push(project[i].getElementsByTagName("p")[0].innerText);
            }
            project_list.push(h,p);
        }
    }else{
        var project_list =[[],[]];
    }
    
    if(document.getElementsByClassName("trophy").length){
        var trophy_list = [];
        var trophy_info = main.getElementsByClassName("trophy")[0];
        var trophy = trophy_info.getElementsByTagName("li");
        if(trophy_info){
            var h = [];p = [];
            for(var i=0;i<trophy.length;i++){
                h.push(trophy[i].getElementsByTagName("h3")[0].innerText);
                p.push(trophy[i].getElementsByTagName("p")[0].innerText);
            }
            trophy_list.push(h,p);
        }
    }else{
        var trophy_list = [[],[]];
    }
    if(document.getElementsByClassName("aboutme").length){
        var aboutme = main.getElementsByClassName("aboutme")[0].getElementsByTagName("p")[0].innerText;
    }else{
        var aboutme = ""
    }
    var number = document.getElementsByTagName("INPUT")[0].value;
    window.JSONARR.push({
        'name':name,
        'position':position,
        'profile':profile_list,
        'contact':contact_list,
        'stack':stack_list,
        'education':education_list,
        'work':work_list,
        'project':project_list,
        'trophy':trophy_list,
        'aboutme':aboutme,
        'number':number,
    })

}

// alert(JSON.stringify(window.JSONARR));
var data = JSON.stringify(window.JSONARR)
console.log(data,typeof(data))

$.ajax({
    type:'POST',
    url:'{% url "cv:create" %}',
    data:data,
    dataType:'json',
    success:function(msg){
        if(msg){
            window.location.href = '{% url "cv:list" %}'
        }
    },
    error:function(xhr,type) {
    
    }
});
}

</script>
{% endif %}

cv/templates/cv/resume_list.html
{% extends "accounts/base.html" %}
{% load static %}
{% block content %}


<link href="{% static 'js/plugs/validate/jquery.validate.css' %}" rel="stylesheet">
<link href="{% static 'css/dw-user.css' %}" rel="stylesheet">
<script src="{% static 'js/dw/responsive-width.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugs/My97DatePickerBeta/My97DatePicker/WdatePicker.js' %}" type="text/javascript"></script>

{% if page_obj %}

<table class="table table-striped">
    <thead>
        <tr>            
        	<th></th>
            <th>标题</th>
            <th>创建人</th>
            <th>创建时间</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
    {% for resume in page_obj %}
        <tr>
            <td align="center">
                <input type="hidden" name="resumeId" value="{{ resume.id }}">
            </td>
            <td align="left">
                <a target="_blank" href="{% url 'cv:preview' resume.id %}" class="titleTag">{{ resume }}</a>
            </td>
            <td align="left" width="100">
                {{ resume.user.username }}
            </td>
            <td align="left">
                {{ resume.created }}
            </td>
            <td align="left">
                <div class="btn-group resumeLeftBtnGroup">
                    <a role="button" class="btn btn-info" href="{% url 'cv:edit' resume.id %}" title="编辑">
                        <i class="fa fa-pencil-square-o"></i>
                    </a>
                    <a role="button" class="btn btn-info" href="{% url 'cv:print' resume.id %}" title="打印">
                        <i class="fa fa-print"></i>
                    </a>
                    <a role="button" class="btn btn-info deleteSurvey" href="{% url 'cv:delete' resume.id %}" title="删除">
                        <i class="fa fa-trash-o fa-fw"></i>
                    </a>
                </div>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% else %}
{# 注释: 这里可以换成自己的对象 #}
    <p>暂无简历信息。</p>
{% endif %}


{# 注释: 下面代码实现分页 #}
{% if is_paginated %}
     <ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% else %}
        <li class="page-item disabled"><span class="page-link">Previous</span></li>
    {% endif %}

    {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="page-item active"><span class="page-link"> {{ i }} <span class="sr-only">(current)</span></span></li>
    	{% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
    {% else %}
        <li class="page-item disabled"><span class="page-link">Next</span></li>
    {% endif %}
    </ul>

{% endif %}

{% endblock %}