accounts/urls.py
from django.urls import path 
from .views import login_view,register_view,logout_view,home,resume

app_name = 'accounts'

urlpatterns = [

    path('resume/',resume,name='resume'),
    path('',home,name='home'),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),

]

cv/urls.py
from django.urls import re_path,path 
from .views import *

app_name = 'cv'

urlpatterns = [
	path('list/',resume_list,name='list'),
	path('create/',create_resume,name='create'),
    re_path(r'^print/(?P<pk>\d+)/$',preview_resume,name='print'),
    re_path(r'^edit/(?P<pk>\d+)/$',preview_resume,name='edit'),
    re_path(r'^preview/(?P<pk>\d+)/$',preview_resume,name='preview'),
    re_path(r'^delete/(?P<pk>\d+)/$',delete_resume,name='delete'),

]

resume/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('',include('cv.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models

from .managers import UserManager

USERNAME_REGEX = '^[a-z0-9._-]*$'


class User(AbstractUser):
    first_name = None
    last_name = None

    username = models.CharField(
        max_length=256,
        unique=True,
        blank=False,
        validators=[
            RegexValidator(
                regex=USERNAME_REGEX,
                message='Username must contain: a-z, 0-9 or ".-_" ',
                code='invalid_username'
                )
            ]
        )

    email = models.EmailField(unique=True, blank=False)

    USERNAME_FIELD = 'email'  # use email to log in
    REQUIRED_FIELDS = ['username']  # required when user is created

    objects = UserManager()

    def __str__(self):
        return self.username

    class Meta:
        verbose_name='用户信息'
        verbose_name_plural = verbose_name

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm

from .models import User


class UserLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email and password:
            user = authenticate(email=email, password=password)
            if not user:
                raise forms.ValidationError("User Does Not Exist.")
            if not user.check_password(password):
                raise forms.ValidationError("Password Does not Match.")
            if not user.is_active:
                raise forms.ValidationError("User is not Active.")

        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegistrationForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ("username","email","password1","password2",)

accounts/views.py
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import render, redirect
from .forms import UserLoginForm, UserRegistrationForm
from .models import User

def home(request):
    return render(request,'accounts/home.html')

def resume(request):
	return render(request,'accounts/resume.html')

def login_view(request):  # users will login with their Email & Password
    if request.user.is_authenticated:
        return redirect("accounts:home")
    else:
        title = "登 陆"
        form = UserLoginForm(request.POST or None)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            # authenticates Email & Password
            user = authenticate(email=email, password=password)
            login(request, user)
            return redirect("accounts:home")
        context = {"form": form,
                   "title": title
                   }

        return render(request, "accounts/form.html", context)


def register_view(request):  # Creates a New Account & login New users
    if request.user.is_authenticated:
        return redirect("accounts:home")
    else:
        title = "注 册"
        form = UserRegistrationForm(request.POST or None)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data.get("password1")
            user.set_password(password)
            user.save()
            new_user = authenticate(email=user.email, password=password)
            login(request, new_user)
            return redirect("accounts:home")

        context = {"title": title, "form": form}

        return render(request, "accounts/form.html", context)


def logout_view(request):  # logs out the logged in users
    if not request.user.is_authenticated:
        return redirect("accounts:login")
    else:
        logout(request)
        return redirect("accounts:home")

accounts/templates/accounts/base.html
{% load staticfiles %}

<html lang="en">
<head>
    <title>{% block title %} 在线简历 {% endblock title %}</title>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Online Resume"> 
    

    <!-- Global CSS -->
    <link rel="stylesheet" href='{% static "/webpage/css/bootstrap.min.css" %}'>   
    <!-- Plugins CSS -->
    <link rel="stylesheet" href='{% static "/webpage/font-awesome/css/font-awesome.css" %}'>
    
    <!-- Theme CSS -->  
    <link id="theme-style" rel="stylesheet" href='{% static "/webpage/css/styles.css" %}'>

</head> 
<body>
    {% include 'accounts/navbar.html' %}
        
    {% block content %}

    {% endblock content %}

    <script type="text/javascript" src="{% static '/webpage/js/jquery-1.11.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/webpage/js/bootstrap.min.js' %}"></script>    
    <!-- custom js -->
    <script type="text/javascript" src="{% static '/webpage/js/main.js' %}"></script>            
</body>
</html> 

accounts/templates/accounts/form.html
{% extends "accounts/base.html" %}
{% load crispy_forms_tags %}

{% block title %} {{ title }}| {{ block.super }}{% endblock title %}

{% block content %}
<div class="container">
<h2>{{ title }}</h2>
<hr>
<form method="POST" action="">
	{% csrf_token %}
	{{ form|crispy }}
    <br>
	<input class="btn btn-success" type="submit" value='{{ title }}'>&nbsp; &nbsp;
    {% if request.path == "/login/" %}
    Don't Have an Account <a href="{% url 'accounts:register' %}">Register Here.</a>
    {% else %}
    Have an Account <a href="{% url 'accounts:login' %}">Login Here.</a>
    {% endif %}
</form>
</div>
{% endblock content %}

accounts/templates/accounts/home.html
{% extends "accounts/base.html" %}

{% block content %}

    <div class="page-header">
      <h1>在线 简历 <small>创建你的简历</small></h1>
    </div>

    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          关于我们
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <p>xxxxxxxxxxxxxxxxxxxxxxxxx</p>
        <p>xxxxxxxxxxxxxxxxxxxxxxxxx</p>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          关于本站
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        <p>xxxxxxxxxxxxxxxxxxxxxxxxx</p>
        <p>xxxxxxxxxxxxxxxxxxxxxxxxx</p>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

accounts/templates/accounts/navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'accounts:home' %}">在线简历</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'cv:list' %}">我的简历</a></li>
        <li><a href="{% url 'cv:create' %}">创建简历</a></li>
        {% endif %}
        {% if request.path == "/create/" %}
        <li onclick="JsonData()"><a href="#">保存简历</a></li>
        {% endif %}
        {% if edit %}
        <li onclick="JsonData()"><a href="#">保存简历</a></li>
        {% endif %}
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        {% if request.user.is_authenticated %}
        <li><a href="#">{{ request.user.username }}</a></li>
        <li><a href="{% url 'accounts:logout' %}">注销</a></li>
        {% else %}
        <li><a href="{% url 'accounts:login' %}">登陆</a></li>
        <li><a href="{% url 'accounts:register' %}">注册</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>